# Generated by Django 2.2 on 2019-04-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190407_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
