# Generated by Django 2.2 on 2019-04-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='key',
        ),
    ]
