# Generated by Django 2.2 on 2019-04-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.BinaryField(default=b''),
        ),
    ]
